# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  connectionType: Kubernetes Service Connection


steps:
- task: Kubernetes@1
  inputs:
    connectionType: $(connectionType)
    kubernetesServiceEndpoint: 'bonitaonk8-01-default'
    namespace: 'default'
    command: 'get'
    arguments: nodes



