apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita-front
  template:
    metadata:
      labels:
        app: bonita-front
    spec:
      containers:
      - name: bonita-front
        image: bonitatest.azurecr.io/bonita:7.10
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: 192.168.2.4
          - name: DB_VENDOR
            value: postgres
          - name: DB_ADMIN_USER
            value: postgres
          - name: DB_ADMIN_PASS
            value: 
          - name: TENANT_PASSWORD
            value: bonita
          - name: TENANT_LOGIN
            value: bonita
---
apiVersion: v1
kind: Service
metadata:
  name: bonita-front
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: bonita-front