apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonita-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonita-front
  template:
    metadata:
      labels:
        app: bonita-front
    spec:
      containers:
      - name: bonita-front
        image: bonitatest.azurecr.io/bonita:7.10
        ports:
        - containerPort: 8080
        env:
          - name: DB_HOST
            value: posgresql4bonita.postgres.database.azure.com
          - name: DB_PORT
            value: "5432"
          - name: DB_VENDOR
            value: postgres
          - name: DB_ADMIN_USER
            value: usuario@posgresql4bonita
          - name: DB_ADMIN_PASSWORD
            value: 1*clavemaquina
          - name: DB_NAME
            value: bonitadb
          - name: DB_USER
            value: bonitauser
          - name: DB_PASS
            value: bonitapass
        
---
apiVersion: v1
kind: Service
metadata:
  name: bonita-front
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: bonita-front